apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    volumeMounts:
    - name: my-secrets
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: my-secrets
    secret:
      secretName: fraud-secret-prod

# *** Exec into this container to see secrets: ***
#
# kubectl exec -it mypod -- /bin/sh